### ISSUE TITLE
[Feature Request]: Pva aanpassen

### ISSUE THREAD

**Issue by koenvanoostrom** [KaanMol/FestivalPlanner-1.3#9]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/KaanMol/FestivalPlanner-1.3/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

kijken bij de feedback van Sanne, en aan de hand daarvan het PvA aanpassen

### Proposed Solution

PvA aanpassen aan de hand van de feedback van Sanne

### Alternatives Considered

verder nog een beetje kijken wat er nodig is en wat verbeterd zou kunnen worden

**Comment by KaanMol** [comment]
Kan ik hier een statusupdate voor krijgen? @koenvanoostrom @OwenVerhoeven

**Comment by OwenVerhoeven** [comment]
De feedback op hoofdstuk 1 tm 4 ga ik zo verwerken. Heb met Koen afgesproken morgen samen nog even erdoorheen te kijken zodat het vervolgens als geheel ingeleverd kan worden.

------- Original Message -------
